name = "cloudflare-worker-honojs-atproto-oauth"
main = "src/index.ts"
compatibility_date = "2024-12-25"

# compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "atproto-oauth-auth-store"
